GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/3

###

GET http://localhost:3000/movies/search?year=2022

###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "name": "Tenet",
  "year": 2020,
  "genres": [
    "action",
    "mind blown"
  ]
}

###

DELETE http://localhost:3000/movies/999

###

